services:
    #Postgres database
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password
    # Redis database       
    redis:
        image: 'redis:latest'
        command: ["redis-server", "--protected-mode", "no"]
    #Express API Server
    api:
        build:
            context: ./server
        image: docker.io/saranya307/complex-api
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    #React client
    client:
        build: ./client
        image: docker.io/saranya307/complex-client
    #Worker service
    worker:
        build: ./worker
        image: docker.io/saranya307/complex-worker
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379     
   #Nginx service
    nginx:
        depends_on:
            - api
            - client
        restart: always
        build:
            context: ./nginx
        ports:
            - '8082:80'